name: CI

on:
  push:
    paths-ignore:
      - "**.md"
      - "**.png"

env:
  RUST_TOOLCHAIN: nightly
  TOOLCHAIN_PROFILE: minimal
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  lints:
    name: Run cargo fmt and cargo clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install nightly toolchain
        run: |
          rustup default nightly

      - name: Run cargo fmt
        run: |
          cargo fmt --all -- --check

      - name: Run cargo check with no default features
        run: |
          cargo check --no-default-features

      - name: Run cargo check with all features
        run: |
          cargo check --all-features

      - name: Run cargo clippy
        run: |
          cargo clippy -- -Dwarnings

  test:
    name: Run cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        run: |
          rustup default nightly

      - name: Run cargo test --no-run
        run: |
          cargo test --all-features --no-run

      - name: Run cargo test
        run: >
          ulimit -Sl 512 && ulimit -Hl 512 &&
          RUSTUP_TOOLCHAIN=nightly cargo test --all-features

  test-macos:
    name: Run cargo test on macos
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        run: |
          rustup default nightly

      - name: Run cargo test
        run: |
          cargo test --all-features
